import { mkdirSync } from 'node:fs';
import { Database } from 'bun:sqlite';
import { config } from '../config/env';

mkdirSync(config.dataDir, { recursive: true });
export const db = new Database(Bun.env.RUBICK_DB ?? `${config.dataDir}/rubick.sqlite`, { create: true });

db.exec(`
  CREATE TABLE IF NOT EXISTS agent_nodes (id TEXT PRIMARY KEY, parent_id TEXT, name TEXT NOT NULL, role TEXT NOT NULL, kind TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, environment_id TEXT, prompt_text TEXT NOT NULL DEFAULT '');
  CREATE TABLE IF NOT EXISTS agent_environments (id TEXT PRIMARY KEY, name TEXT NOT NULL, source_path TEXT NOT NULL, installed_path TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, title TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS runs (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, node_id TEXT NOT NULL, status TEXT NOT NULL, input TEXT NOT NULL, output TEXT, started_at TEXT NOT NULL, finished_at TEXT);
  CREATE TABLE IF NOT EXISTS run_logs (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, source TEXT NOT NULL, level TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS agent_usages (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, run_id TEXT NOT NULL, node_id TEXT NOT NULL, environment_id TEXT NOT NULL, created_at TEXT NOT NULL);
`);
try { db.exec('ALTER TABLE agent_nodes ADD COLUMN environment_id TEXT'); } catch { /* Existing database already has the migration. */ }
try { db.exec("ALTER TABLE agent_nodes ADD COLUMN prompt_text TEXT NOT NULL DEFAULT ''"); } catch { /* Existing database already has the migration. */ }
try { db.exec("ALTER TABLE runs ADD COLUMN current_agent TEXT"); } catch { /* Existing database already has the migration. */ }
try { db.exec("ALTER TABLE runs ADD COLUMN current_started_at TEXT"); } catch { /* Existing database already has the migration. */ }

// Remove records generated by the initial fake executor so they cannot look like real runs.
db.exec(`
  DELETE FROM messages WHERE session_id IN (SELECT session_id FROM runs WHERE output LIKE '%模拟模式%');
  DELETE FROM sessions WHERE id NOT IN (SELECT DISTINCT session_id FROM messages);
  DELETE FROM runs WHERE output LIKE '%模拟模式%';
`);

const count = db.query('SELECT COUNT(*) as count FROM agent_nodes').get() as { count: number };
if (count.count === 0) {
  const insert = db.prepare('INSERT INTO agent_nodes (id,parent_id,name,role,kind) VALUES (?,?,?,?,?)');
  insert.run('root-orchestrator', null, '总协调 Agent', '对外入口与任务分派', 'builtin');
  insert.run('product-agent', 'root-orchestrator', '产品 Agent', '理解目标，组织产品工作', 'business');
  insert.run('delivery-agent', 'root-orchestrator', '交付 Agent', '汇总产物并交付给用户', 'business');
  insert.run('developer-agent', 'product-agent', '开发人员 Agent', '实现和修改代码', 'business');
  insert.run('qa-agent', 'product-agent', '测试人员 Agent', '验证功能和发现问题', 'business');
}
